# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Files are excluded if they're generated and shouldn't be autoformatted
# gui.py is excluded because it uses a u"..." (unicode string), and the u would be removed
# Large files, such as images, are excluded from the large file check
exclude: stylesheet.qss|resources.py|gui.py|docs/_static/QtDesigner.jpg|docs/_static/nr_demo.gif
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
    -   id: black-jupyter

# Source: https://github.com/NIRALUser/NeuroRuler/issues/97
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.3.0'
    hooks:
    -   id: mypy
        additional_dependencies: ["types-toml", "opencv-stubs==0.0.8", "types-click"]
        args: ["--config-file=pyproject.toml"]
        exclude: "tests/"
